# External plugins
# See http://ixti.net/software/2013/01/28/using-jekyll-plugins-on-github-pages.html for making `jekyll archives` work.
plugins:
  - jekyll-archives # Sorry, not GitHub pages friendly!
  - jekyll-sitemap
  - jekyll-paginate-v2
  - jekyll-feed
  - jekyll-paginate

exclude:
  - "/vendor/"

include:
  - _posts

# Site settings
title: ファウンデーション
subtitle: "The lowest load-bearing part of a building."
email: rukaszzq@gmail.com
name: Rukaszz
description: >
  日々の学びを出力するブログです．
# Base URL of site (i.e. /blog). It should always start with a slash,
# and never end with a slash. Set it to a blank value if hosting at the
# root of your server.
#baseurl: "https://rukaszz.github.io/blog/" # the subpath of your site, e.g. /blog/
#baseurl: "" # for test
#url: "https://rukaszz.github.io/" # the base hostname & protocol for your site
url: "http://127.0.0.1:4000" # for test
cover: "/assets/header_image.jpg"
logo: "/assets/logo.png"

# Build settings
markdown: kramdown
inter_post_navigation: false
highlightjs_theme: "monokai-sublime"

# Pagination Settings
# https://github.com/sverrirs/jekyll-paginate-v2/blob/master/README-GENERATOR.md#site-configuration
pagination:
  enabled: true
  per_page: 5
  permalink: "/page/:num/"
  sort_reverse: true

collections:
  posts:
    output: true

# Archive settings (see https://github.com/jekyll/jekyll-archives/)
# jekyll-archives:
#   enabled:
#     - categories
#     - tags
#   layout: 'archive'
#   permalinks:
#     category: "/category/:name/"
#     tag: "/tag/:name/"
#     posts: "/posts/:name/"
jekyll-archives:
  enabled: all
  layouts:
    category: category
  permalinks:
    category: "/category/:name/"

# Disqus comments
# disqus_shortname: bencentra

# Google analytics
# ga_tracking_id: "UA-XXXX-1"

# Category descriptions (for archive pages)
# descriptions:
#   - cat: "jekyll"
#     desc: "Posts describing Jekyll setup techniques."
#   - cat: "dummy"
#     desc: "Just some placeholder posts, lorem ipsum and the rest."
#   - cat: "C++"
#     desc: "C++ learning outputs here."
#   - cat: "AWS"
#     desc: "Aws learning outputs here."
#   - cat: "Docker"
#     desc: "Docker learning outputs here."
#   - cat: "git"
#     desc: "git learning outputs here."

categories:
  cpp:
    desc: "C++ learning outputs here"
  AWS:
    desc: "Aws learning outputs here"
  Docker:
    desc: "Docker learning outputs here"
  git:
    desc: "git learning outputs here"
  rust:
    desc: "rust learning outputs here"

# Social icons and sharing options
#
# Social settings are used in two places:
# * In the footer, as links to your personal profiles
# * After each blog post for sharing widgets
#
# Example:
#
# social:
#   - name: Twitter                         # Name of the service
#     icon: twitter                         # Font Awesome icon to use (minus fa- prefix)
#     username: "@TheBenCentra"             # (User) Name to display in the footer link
#     url: https://twitter.com/TheBenCentra # URL of your profile (leave blank to not display in footer)
#     desc: Follow me on Twitter            # Description to display as link title, etc
#     share: true                           # Include in the "Share" section of posts
social:
  - name: GitHub
    icon: github
    username: bencentra
    url: https://github.com/rukaszz
    desc: Fork me on GitHub
    share: false

# Social sharing protocols
# These are for automatically generating sharing metadata for FB and Twitter
# OS Protocol is for sharing the source of your site, if you're interested. For more, see osprotocol.com
protocols:
    fb_image: "/assets/logo.png"
    fb_image_width: 612
    fb_image_height: 605
    fb_image_type: "image/png"

    twitter_image: "/assets/logo.png"

    os_repo: "https://github.com/bencentra/centrarium.com"
    os_rcs_type: "git"
    os_src: "git@github.com:bencentra/centrarium.com.git"
